import { questionsData } from '../data/questions';

export function generateMarkdown(answers) {
    let md = `# Project Working Agreement\n\n`;

    // Custom header based on project name if available
    if (answers.projectName) {
        md = `# ${answers.projectName} - Working Agreement\n\n`;
    }

    questionsData.forEach(category => {
        md += `## ${category.category}\n\n`;

        category.questions.forEach(q => {
            const answer = answers[q.id];
            if (!answer) return;

            md += `### ${q.label}\n`;

            if (Array.isArray(answer)) {
                answer.forEach(item => {
                    md += `- ${item}\n`;
                });
            } else {
                md += `${answer}\n`;
            }
            md += `\n`;
        });
    });

    md += `---\nGenerated by Project Initialization Tool`;
    return md;
}
