import { questionsData } from '../data/questions';

const getAnswer = (answers, q) => {
    const val = answers[q.id];
    if (!val) return null;

    // Handle dynamic list (objects)
    if (q.type === 'dynamic-list') {
        if (!Array.isArray(val) || val.length === 0) return null;
        return val.map(item => `${item.name}: ${item.time}`).join("\n");
    }

    // Handle structured list
    if (q.type === 'structured-list') {
        if (!Array.isArray(val) || val.length === 0) return null;

        // Specialized formatting for Team Composition
        if (q.id === 'members') {
            return val.map(item => `${item.name} - ${item.role} ${item.focus ? `(${item.focus})` : ''}`).join("\n");
        }
        if (q.id === 'stakeholders') {
            return val.map(item => `${item.name} (${item.title})`).join("\n");
        }

        // Generic / Meeting format
        return val.map(item => {
            const freq = item.frequency ? `${item.frequency} ` : '';
            const day = (item.day && item.day !== '-') ? `on ${item.day} ` : '';
            const time = item.time ? `@ ${item.time}` : '';
            return `${item.name}: ${freq}${day}${time}`;
        }).join("\n");
    }

    // Handle multi-select
    return Array.isArray(val) ? val.join(", ") : val;
};

export function generateMarkdown(answers) {
    let md = `# ${answers.projectName || "Team Charter"}\n\n`;
    if (answers.mission) md += `> ${answers.mission}\n\n`;

    questionsData.forEach(category => {
        md += `## ${category.category}\n\n`;
        category.questions.forEach(q => {
            const val = getAnswer(answers, q);
            if (val) {
                if (q.type === 'dynamic-list' || q.type === 'structured-list') {
                    md += `### ${q.label}\n`;
                    val.split('\n').forEach(line => md += `- ${line}\n`);
                    md += '\n';
                } else {
                    md += `### ${q.label}\n${val}\n\n`;
                }
            }
        });
    });
    md += `---\nGenerated by Project Initialization Tool`;
    return md;
}

export function generateJira(answers) {
    let jira = `h1. ${answers.projectName || "Team Charter"}\n\n`;
    if (answers.mission) jira += `{quote}${answers.mission}{quote}\n\n`;

    questionsData.forEach(category => {
        jira += `h2. ${category.category}\n`;
        jira += `{panel:title=${category.category}|borderStyle=dashed|borderColor=#ccc|titleBGColor=#f7f7f7|bgColor=#ffffff}\n`;
        category.questions.forEach(q => {
            let val = getAnswer(answers, q);
            if (val) {
                if (q.type === 'dynamic-list' || q.type === 'structured-list') {
                    jira += `*${q.label}*:\n`;
                    val.split('\n').forEach(line => jira += `** ${line}\n`);
                } else {
                    jira += `*${q.label}*: ${val}\n`;
                }
            }
        });
        jira += `{panel}\n\n`;
    });
    return jira;
}

export function generateSlack(answers) {
    let slack = `*${answers.projectName || "Team Charter"}*\n`;
    if (answers.mission) slack += `> _${answers.mission}_\n\n`;

    questionsData.forEach(category => {
        slack += `\n*${category.category}*\n`;
        category.questions.forEach(q => {
            let val = getAnswer(answers, q);
            if (val) {
                if (q.type === 'dynamic-list' || q.type === 'structured-list') {
                    slack += `• *${q.label}*:\n`;
                    val.split('\n').forEach(line => slack += `     ◦ ${line}\n`);
                } else {
                    slack += `• *${q.label}*: ${val}\n`;
                }
            }
        });
    });

    return slack;
}
